[package]
name = "ybc"
version = "0.0.0"
description = "A Yew component library based on the Bulma CSS framework."
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
derive_more = "0.99.9"
mixin = "0.2.0"
web-sys = { version="0.3", features=["Element", "File", "HtmlCollection", "HtmlSelectElement"] }
yew = { git="https://github.com/siku2/yew.git", branch="optional-attribute", features=["web_sys"] }
yewtil = { git="https://github.com/siku2/yew.git", branch="optional-attribute", features=["neq"] }
yew-router = { git="https://github.com/siku2/yew.git", branch="optional-attribute", features=["web_sys"], optional=true }

[features]
default = ["router"]
router = ["yew-router"]
